In [1]:
!nvidia-smi


Tue Apr  7 20:44:41 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.57                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   46C    P8             13W /   80W |     966MiB /   6144MiB |      5%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu130


In [3]:
#scalar

scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7, 7])
print(vector)


tensor([7, 7])


In [7]:
vector.ndim


1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim


2

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
#tensor
tensor = torch.tensor(([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]],
                                    [[10, 11, 12],
                                    [13, 14, 15],
                                    [16, 17, 18]]]))

tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([2, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
tensor[0][2][1]

tensor(8)

In [19]:
tensor[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [20]:
#random tensors

In [21]:
rand_tensor = torch.rand(3, 4)

In [23]:
one_to_ten = torch.arange(start = 0, end = 10, step = 1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.__version__

'2.11.0+cu130'

In [26]:
one_to_more = torch.arange(start = 0, end = 1000, step = 47)
one_to_more

tensor([  0,  47,  94, 141, 188, 235, 282, 329, 376, 423, 470, 517, 564, 611,
        658, 705, 752, 799, 846, 893, 940, 987])

In [30]:
ten_zeros = torch.zeros_like(input = one_to_ten)

In [31]:
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])