In [2]:
!nvidia-smi


Fri Apr 10 10:14:20 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.57                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   43C    P8             13W /   80W |     654MiB /   6144MiB |     15%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu130


In [4]:
#scalar

scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7, 7])
print(vector)


tensor([7, 7])


In [8]:
vector.ndim


1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim


2

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
#tensor
tensor = torch.tensor(([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]],
                                    [[10, 11, 12],
                                    [13, 14, 15],
                                    [16, 17, 18]]]))

tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([2, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
tensor[0][2][1]

tensor(8)

In [20]:
tensor[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [21]:
#random tensors

In [22]:
rand_tensor = torch.rand(3, 4)

In [23]:
one_to_ten = torch.arange(start = 0, end = 10, step = 1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.__version__

'2.11.0+cu130'

In [25]:
one_to_more = torch.arange(start = 0, end = 1000, step = 47)
one_to_more

tensor([  0,  47,  94, 141, 188, 235, 282, 329, 376, 423, 470, 517, 564, 611,
        658, 705, 752, 799, 846, 893, 940, 987])

In [26]:
ten_zeros = torch.zeros_like(input = one_to_ten)

In [27]:
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
# tensor datatypes

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float32)

In [30]:
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = torch.float16, # datatype of memory of storage of numbers
                               device = None, # cuda or cpu, what device is tensor on
                               requires_grad = False # whether to track gradients for this tensor
                               )

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [33]:
float_multiple =float_32_tensor * float_16_tensor
float_multiple.dtype


torch.float32

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)

In [35]:
multi_int_float_tensor = int_32_tensor * float_32_tensor

In [36]:
multi_int_float_tensor.dtype

torch.float32

### Getting information from tensors 

1. Get data type form tensor use tensor.dtype
2. for get shape of tensor we have to use tensor.shape
3. and when we want right debices from tensor we use tensor.device

In [37]:
#Create a tensor

tensor = torch.rand(3, 4, dtype = torch.float16, device = 'cuda')
tensor

tensor([[0.8184, 0.4131, 0.2847, 0.7734],
        [0.9155, 0.6001, 0.2430, 0.1996],
        [0.4333, 0.0201, 0.3723, 0.9575]], device='cuda:0',
       dtype=torch.float16)

In [38]:
#Find details about tensor
print(tensor)

tensor([[0.8184, 0.4131, 0.2847, 0.7734],
        [0.9155, 0.6001, 0.2430, 0.1996],
        [0.4333, 0.0201, 0.3723, 0.9575]], device='cuda:0',
       dtype=torch.float16)


In [39]:
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Size of tensor: {tensor.size}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cuda:0
Size of tensor: <built-in method size of Tensor object at 0x7ed15febb6a0>


### Manipulating Tensors

Tensor operations include:
* Addidtion
* Subtraction
* Multiplication
* Division
* Matrix multiplication

#Create tensor

In [40]:
tensor = torch.tensor([1, 2, 3])

In [41]:
tensor + 10

tensor([11, 12, 13])

In [42]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [43]:

tensor

tensor([1, 2, 3])

In [44]:
#Substract

tensor - 10

tensor([-9, -8, -7])

In [45]:
tensor // 10 

tensor([0, 0, 0])

In [46]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways to multiplicate i nneural network and deep leargnin


1. Element-wise multipiocatiojn

2. Matrix mulitplication

In [47]:
#Element wise multiplication

print(tensor, "*", tensor)
print(f'Equals: {tensor * tensor}')


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
tensor

tensor([1, 2, 3])

In [50]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
    
value

CPU times: user 0 ns, sys: 2.57 ms, total: 2.57 ms
Wall time: 3.03 ms


tensor(14)

In [51]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 440 μs, sys: 0 ns, total: 440 μs
Wall time: 414 μs


tensor(14)

In [52]:
# Shape error
tensor_shape = torch.rand(3, 5)

In [53]:
# tensor error with shape torch.matmul(tensor_shape, tensor_shape)

In [54]:
tensor_shape2 = torch.rand(5, 3)

In [55]:
#this two shapes works for matmul functionality

torch.matmul(tensor_shape2, tensor_shape)

#diffrent of shapes for matmul functionality
torch.matmul(tensor_shape, tensor_shape2)

tensor([[0.8269, 1.3447, 0.6540],
        [1.1132, 1.3400, 1.2128],
        [0.4927, 1.0818, 1.0184]])

In [56]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix our tensor shape issues we can manipulate the shape of one of ours tensors using a *transpose 

In [ ]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensor_B, tensor_B.T).shape

torch.Size([3, 3])

### Using function for get min max mean sum etc (tensor aggregation)

In [74]:
x = torch.arange(1, 100 , 7)
x, x.dtype

(tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99]),
 torch.int64)

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
torch.min(x), torch.max(x), x.dtype #torch.mean(x) have to be float no int like here,


(tensor(0), tensor(90), torch.int64)

In [68]:
torch.sum(x)

tensor(450)

In [69]:
x.sum()

tensor(450)

In [63]:
torch.mean(x, dtype = torch.float32)

tensor(45.)

### Finding the positional min and max

In [75]:
x

tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [76]:
x.argmin()

tensor(0)

In [77]:
x.argmax()

tensor(14)

In [78]:
x[0]

tensor(1)

In [79]:
x[9]

tensor(64)

## Reshaping, stacking, squeezing and unsqueezing tesnors

* Reshaping - reshapes an input tensor to other shape

* View - other view but keep shape of memory as origin one

* Stacking - combine tensor to be on top of each other(vstack) or side by side using (hstack)

* Squeeze - removes 1 from tesors dimension 

* Unsquezze - add 1 to dimensions

* Permute - swapp dimension permuted in certain way

In [81]:
x = torch.arange(1., 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [87]:
#Add extra dimenison

x_reshaped = x.reshape(1, 9)
x_reshaped2 = x.reshape(3, 3)
x_reshaped, x_reshaped.shape , x_reshaped2, x_reshaped2.shape   

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [99]:
# Change the view
x_view = x.view(3, 3)
x_view, x_view.shape

print(x.view(3, 3))
print(x)
print(x.reshape(3, 3))
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [105]:
y = torch.arange(1., 28., 3.)
y

tensor([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [109]:
y_reshaped = y.reshape(3, 3)

torch.stack((x_reshaped2, y_reshaped), dim = 0)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[ 1.,  4.,  7.],
         [10., 13., 16.],
         [19., 22., 25.]]])