In [2]:
!nvidia-smi


Thu Apr  9 16:22:41 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.57                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  |   00000000:01:00.0  On |                  N/A |
| N/A   47C    P8             13W /   80W |     718MiB /   6144MiB |     22%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu130


In [4]:
#scalar

scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7, 7])
print(vector)


tensor([7, 7])


In [8]:
vector.ndim


1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim


2

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
#tensor
tensor = torch.tensor(([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]],
                                    [[10, 11, 12],
                                    [13, 14, 15],
                                    [16, 17, 18]]]))

tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([2, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
tensor[0][2][1]

tensor(8)

In [20]:
tensor[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [21]:
#random tensors

In [22]:
rand_tensor = torch.rand(3, 4)

In [23]:
one_to_ten = torch.arange(start = 0, end = 10, step = 1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.__version__

'2.11.0+cu130'

In [25]:
one_to_more = torch.arange(start = 0, end = 1000, step = 47)
one_to_more

tensor([  0,  47,  94, 141, 188, 235, 282, 329, 376, 423, 470, 517, 564, 611,
        658, 705, 752, 799, 846, 893, 940, 987])

In [26]:
ten_zeros = torch.zeros_like(input = one_to_ten)

In [27]:
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
# tensor datatypes

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float32)

In [30]:
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = torch.float16, # datatype of memory of storage of numbers
                               device = None, # cuda or cpu, what device is tensor on
                               requires_grad = False # whether to track gradients for this tensor
                               )

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [33]:
float_multiple =float_32_tensor * float_16_tensor
float_multiple.dtype


torch.float32

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)

In [35]:
multi_int_float_tensor = int_32_tensor * float_32_tensor

In [36]:
multi_int_float_tensor.dtype

torch.float32

### Getting information from tensors 

1. Get data type form tensor use tensor.dtype
2. for get shape of tensor we have to use tensor.shape
3. and when we want right debices from tensor we use tensor.device

In [37]:
#Create a tensor

tensor = torch.rand(3, 4, dtype = torch.float16, device = 'cuda')
tensor

tensor([[0.2422, 0.6636, 0.7866, 0.5410],
        [0.7109, 0.1754, 0.3293, 0.3381],
        [0.0834, 0.2776, 0.8037, 0.0705]], device='cuda:0',
       dtype=torch.float16)

In [38]:
#Find details about tensor
print(tensor)

tensor([[0.2422, 0.6636, 0.7866, 0.5410],
        [0.7109, 0.1754, 0.3293, 0.3381],
        [0.0834, 0.2776, 0.8037, 0.0705]], device='cuda:0',
       dtype=torch.float16)


In [39]:
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Size of tensor: {tensor.size}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cuda:0
Size of tensor: <built-in method size of Tensor object at 0x7a6c75ba7830>


### Manipulating Tensors

Tensor operations include:
* Addidtion
* Subtraction
* Multiplication
* Division
* Matrix multiplication

#Create tensor

In [40]:
tensor = torch.tensor([1, 2, 3])

In [41]:
tensor + 10

tensor([11, 12, 13])

In [42]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [43]:

tensor

tensor([1, 2, 3])

In [44]:
#Substract

tensor - 10

tensor([-9, -8, -7])

In [45]:
tensor // 10 

tensor([0, 0, 0])

In [46]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways to multiplicate i nneural network and deep leargnin


1. Element-wise multipiocatiojn

2. Matrix mulitplication

In [52]:
#Element wise multiplication

print(tensor, "*", tensor)
print(f'Equals: {tensor * tensor}')


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [53]:
torch.matmul(tensor, tensor)

tensor(14)

In [54]:
tensor

tensor([1, 2, 3])

In [56]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
    
value

CPU times: user 0 ns, sys: 1.87 ms, total: 1.87 ms
Wall time: 1.45 ms


tensor(14)

In [57]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 98 μs, sys: 0 ns, total: 98 μs
Wall time: 103 μs


tensor(14)